openapi: 3.0.1
info:
  title: dev-kinect-event-processor-app
  description: ''
  version: v1
servers:
  - url: https://dev.kinectmessaging.com/event/v1
paths:
  /*:
    post:
      summary: dev-kinect-event-processor-app_POST
      operationId: 67057c699596c8b363abaf22
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]